# Site settings
title: Steven R. Young PhD
header-img: img/home-bg.jpg
email: stevenryoung@gmail.com
description: "Personal website of Steven R. Young PhD."
baseurl: ""
url: "http://stevenryoung.com"
twitter_username: stevenryoungphd
github_username: stevenryoung
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate_path: "blog/page:num/"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

pages_list: {'Home':'/', 'About':'/about', 'Blog':'/blog/', 'Contact': '/contact'}
